### ISSUE TITLE
Unnecessary copying makes sampling time explode

### ISSUE THREAD

**Issue by carlo-** [TianhongDai/hindsight-experience-replay#1]
Hello,
I noticed that the training time increases linearly at each epoch, in fact, it seems to scale up as the buffer size increases. After a bit of research, I think that the reason is the `.copy()` in [this](https://github.com/TianhongDai/hindsight-experience-replay/blob/65110d16193ce5921e9b899942ae65f7f8c503ff/replay_buffer.py#L44) line of the sampling function. 

I might have missed something, but it seems that the copying is not needed; the original implementation in baselines also [doesn't have this](https://github.com/openai/baselines/blob/5b41c926c7a852df3f0928afdf2429f96a3965cb/baselines/her/replay_buffer.py#L45). I removed it and it seems to fix the issue.

**Comment by TianhongDai** [comment]
@carlo- Hi Carlo, Sorry for reply so late! Thanks you so much for the suggestion and I have removed the `.copy()` term.

**Comment by carlo-** [comment]
Happy to help!
