### ISSUE TITLE
glfwGetVideoMode: Assertion `monitor != ((void *)0)' failed. Aborted (core dumped)

### ISSUE THREAD

**Issue by nizhihao** [TianhongDai/hindsight-experience-replay#12]
When i evalute the performance with python demo.py --env-name='FetchReach-v1', there is a bug as below:

Creating window glfw
python: /builds/florianrhiem/pyGLFW/glfw-3.3.3/src/monitor.c:447: glfwGetVideoMode: Assertion `monitor != ((void *)0)' failed.
Aborted (core dumped)

i have try to solve it, but i can't find out the good.  
could you give me some ideas. Tanks very much!

**Comment by TianhongDai** [comment]
@nizhihao It should be the problem of glfw, I use the `glfw==1.8.2`, could you try to downgrade it, please?

**Comment by nizhihao** [comment]
@TianhongDai  yeah, the problem is the version of the glfw.  and I used the `glfw==2.1.0`, Thanks very much !!

**Comment by TianhongDai** [comment]
@nizhihao You're welcome!
