### ISSUE TITLE
Some questions about distributed reinforcement learning

### ISSUE THREAD

**Issue by namjiwon1023** [TianhongDai/hindsight-experience-replay#17]
@TianhongDai Thank you for writing the perfect HER code, But I want to implement multi-process, multi-GPU or MPI in my code, but I have no idea, maybe you can give me some hints, can i communicate with you in WeChat Or other communication apps? Want to make a friend! Waiting for your reply.

**Comment by TianhongDai** [comment]
@namjiwon1023 Hi, Could I know what is your wechat id, and we can have a chat.

**Comment by namjiwon1023** [comment]
@TianhongDai  Thank you for your reply！ My WeChat ID : nzy1414117007.

**Comment by TianhongDai** [comment]
@namjiwon1023 Hi - I have added you.

**Comment by jonyzhang2023** [comment]
> @namjiwon1023 Hi, Could I know what is your wechat id, and we can have a chat.
@TianhongDai 
hi can i add you too pls ? i have the same question~
my wechat is JonyZhang3
