### ISSUE TITLE
Clipping target q values

### ISSUE THREAD

**Issue by Medabid1** [TianhongDai/hindsight-experience-replay#2]
Hello, I would like to ask question about clipping target q values to just negative numbers in : 
https://github.com/TianhongDai/hindsight-experience-replay/blob/master/ddpg_agent.py#L216

Is it due to the fact that the reward is always less than zero, thus the values should be always less than zero ? 

Thanks in advance !

**Comment by TianhongDai** [comment]
@Medabid1 Hi - you're right, because the reward for the fetch environment only have -1 (failed) or 0 (success). Therefore, the return will never be a positive value.
