### ISSUE TITLE
Performance on FetchReach-v0

### ISSUE THREAD

**Issue by ArshT** [TianhongDai/hindsight-experience-replay#27]
The policy for the FetchReach task seems to converge much faster than in the original report, considering the fact that the given command in the ReadMe should result in 10 * 2 * 50 = 1000 timesteps per epoch, while the HER OpenAI report has about 95k timesteps in a single epoch. Is there a reason why this implementation does much better?? Am I missing something?

**Comment by AdamJJZ** [comment]
did u figure out the reason behind this yet?

**Comment by ArshT** [comment]
Hi
I apologize for the late reply. I think the improved performance relates to the normalization, As far as I remember, the original paper did not have this.
