### ISSUE TITLE
why lock?

### ISSUE THREAD

**Issue by deeplearnerJHB** [TianhongDai/hindsight-experience-replay#3]
Hello, thank you for your work. Here, some codes confuses me. Why do you use threading.Lock? I don't find any code about multi-threading in your project, thus there is no need for setting lock, isn't it?

**Comment by TianhongDai** [comment]
@deeplearnerJHB Yes, you are right, `threading.Lock` can be removed.

**Comment by TianhongDai** [comment]
`threading.Lock` has been removed in the latest version.
