### ISSUE TITLE
How to obtain plots?

### ISSUE THREAD

**Issue by RyanRizzo96** [TianhongDai/hindsight-experience-replay#5]
Hi, how do you obtain the plotsshowing success rate? Do you load and plot from `model.pt`,  or do you use different software to obtain the plots shown in the readme?

Thanks!

**Comment by stefanwanckel** [comment]
@RyanRizzo96 Did you find an answer to the this issue? I am asking myself the same thing.
o_mean and g_mean only contain 1 position and not an array.
