### ISSUE TITLE
How to debug your code in Pycharm?

### ISSUE THREAD

**Issue by fuxianh** [TianhongDai/hindsight-experience-replay#8]
@TianhongDai Hi, Tianhong. Very glad to find your implementation of HER in Pytorch, I would like to use as a baseline to do my own research, however I find it hard to debug with Pycharm, some errors shows up. Could you give me some help? if possible, we can talk in wechat, I have send you my id to your email. Thanks a lot.

**Comment by TianhongDai** [comment]
@fuxianh Sure, no problem.
